// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPb_fF515ullCooKAbS8RJKF2UmML0zkI',
    appId: '1:350033650123:web:62977c204684e609aed64e',
    messagingSenderId: '350033650123',
    projectId: 'cloud-messaging-app-goteri141',
    authDomain: 'cloud-messaging-app-goteri141.firebaseapp.com',
    storageBucket: 'cloud-messaging-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPGiTDCJry2477WNbRoV2q7gyZpwuZHrk',
    appId: '1:350033650123:android:eccc4a5c29a49770aed64e',
    messagingSenderId: '350033650123',
    projectId: 'cloud-messaging-app-goteri141',
    storageBucket: 'cloud-messaging-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAspya2QeVhFT9YvYAw037RaBfePkrBJsM',
    appId: '1:350033650123:ios:5eea580b9caab453aed64e',
    messagingSenderId: '350033650123',
    projectId: 'cloud-messaging-app-goteri141',
    storageBucket: 'cloud-messaging-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAspya2QeVhFT9YvYAw037RaBfePkrBJsM',
    appId: '1:350033650123:ios:5eea580b9caab453aed64e',
    messagingSenderId: '350033650123',
    projectId: 'cloud-messaging-app-goteri141',
    storageBucket: 'cloud-messaging-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPb_fF515ullCooKAbS8RJKF2UmML0zkI',
    appId: '1:350033650123:web:ec8e6aef1962f7e1aed64e',
    messagingSenderId: '350033650123',
    projectId: 'cloud-messaging-app-goteri141',
    authDomain: 'cloud-messaging-app-goteri141.firebaseapp.com',
    storageBucket: 'cloud-messaging-app-goteri141.firebasestorage.app',
  );
}
